knife4j:
  enable: true

server:
  port: 8001

spring:
  application:
    name: book-collection

  datasource:
    url: jdbc:mysql://106.53.124.182:3306/Book_Collection_System?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 10 # 池中维护的最小空闲连接数，默认为 10 个。
      maximum-pool-size: 30 # 池中最大连接数，包括闲置和使用中的连接，默认为 10 个。

  redis:
    host: 106.53.124.182
    port: 6379
    database: 1
    timeout: 0
    jedis:
      pool:
        max-active: 20 # 连接池最大连接数，默认为 8 。使用负数表示没有限制。
        max-idle: 8 # 默认连接数最小空闲的连接数，默认为 8 。使用负数表示没有限制。
        min-idle: 0 # 默认连接池最小空闲的连接数，默认为 0 。允许设置 0 和 正数。
        max-wait: -1 # 连接池最大阻塞等待时间，单位：毫秒。默认为 -1 ，表示不限制。


  rabbitmq:
    host: 106.53.124.182
    port: 5672
    virtual-host: /bookcollection
    username: root
    password: root
    publisher-returns: true #消息发送到队列确认
# 我真的不理解为啥邮箱的配置放在yml会爆红？必须得放在properties文件里..... 虽然不影响运行 但是推代码推不上仓库.......
#  mail:
#    host: smtp.qq.com #邮件服务器地址
#    username: 1601709391@qq.com #邮件服务器用户名
#    password: tlxamrtiwmvbiijd #签名
#    default-encoding: UTF-8 #邮件编码格式
#    port: 587 #邮件服务器端口
#    properties:
#      mail:
#      smtp:
#      auth: true
#      socketFactory:
#      class: javax.net.ssl.SSLSocketFactory
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false #关闭缓存

minio:
  endpoint: http://106.53.124.182:9000
  accessKey: OV5xLXR9kUxpO3Oi
  secretKey: w0UvfFW2NNVkVj7N4JeeVUfH1wpEpOFj

thymeleaf:
  prefix: classpath:/templates  #prefix：指定模板所在的目录
  check-template-location: true  #check-tempate-location: 检查模板路径是否存在
  cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
  suffix:  .html
  #encoding: UTF-8
  #content-type: text/html
  mode: HTML5




